# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcomp.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wid_addcomp(object):
    def setupUi(self, wid_addcomp):
        wid_addcomp.setObjectName("wid_addcomp")
        wid_addcomp.resize(1200, 600)
        wid_addcomp.setMinimumSize(QtCore.QSize(900, 0))
        self.horizontalLayout = QtWidgets.QHBoxLayout(wid_addcomp)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbl_facestable = QtWidgets.QTableWidget(wid_addcomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_facestable.sizePolicy().hasHeightForWidth())
        self.tbl_facestable.setSizePolicy(sizePolicy)
        self.tbl_facestable.setMinimumSize(QtCore.QSize(300, 0))
        self.tbl_facestable.setMaximumSize(QtCore.QSize(240, 16777215))
        self.tbl_facestable.setShowGrid(True)
        self.tbl_facestable.setRowCount(0)
        self.tbl_facestable.setObjectName("tbl_facestable")
        self.tbl_facestable.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_facestable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_facestable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbl_facestable.setHorizontalHeaderItem(2, item)
        self.tbl_facestable.horizontalHeader().setVisible(True)
        self.tbl_facestable.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_facestable.horizontalHeader().setDefaultSectionSize(80)
        self.tbl_facestable.horizontalHeader().setHighlightSections(True)
        self.tbl_facestable.horizontalHeader().setMinimumSectionSize(70)
        self.tbl_facestable.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_facestable.horizontalHeader().setStretchLastSection(True)
        self.tbl_facestable.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tbl_facestable)
        self.lay_gl = QtWidgets.QVBoxLayout()
        self.lay_gl.setObjectName("lay_gl")
        self.lbl_gl = QtWidgets.QLabel(wid_addcomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_gl.sizePolicy().hasHeightForWidth())
        self.lbl_gl.setSizePolicy(sizePolicy)
        self.lbl_gl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gl.setObjectName("lbl_gl")
        self.lay_gl.addWidget(self.lbl_gl)
        self.glbox = QtWidgets.QWidget(wid_addcomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glbox.sizePolicy().hasHeightForWidth())
        self.glbox.setSizePolicy(sizePolicy)
        self.glbox.setMinimumSize(QtCore.QSize(300, 300))
        self.glbox.setObjectName("glbox")
        self.lay_gl.addWidget(self.glbox)
        self.horizontalLayout.addLayout(self.lay_gl)
        self.line_4 = QtWidgets.QFrame(wid_addcomp)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.rightBox = QtWidgets.QVBoxLayout()
        self.rightBox.setObjectName("rightBox")
        self.lay_name = QtWidgets.QHBoxLayout()
        self.lay_name.setObjectName("lay_name")
        self.lbl_name = QtWidgets.QLabel(wid_addcomp)
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.lay_name.addWidget(self.lbl_name)
        self.ln_name = QtWidgets.QLineEdit(wid_addcomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_name.sizePolicy().hasHeightForWidth())
        self.ln_name.setSizePolicy(sizePolicy)
        self.ln_name.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_name.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_name.setObjectName("ln_name")
        self.lay_name.addWidget(self.ln_name)
        self.rightBox.addLayout(self.lay_name)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(wid_addcomp)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.ln_cat = QtWidgets.QLineEdit(wid_addcomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_cat.sizePolicy().hasHeightForWidth())
        self.ln_cat.setSizePolicy(sizePolicy)
        self.ln_cat.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_cat.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_cat.setObjectName("ln_cat")
        self.horizontalLayout_5.addWidget(self.ln_cat)
        self.rightBox.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(wid_addcomp)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.rightBox.addWidget(self.line)
        self.lbl_set = QtWidgets.QLabel(wid_addcomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_set.sizePolicy().hasHeightForWidth())
        self.lbl_set.setSizePolicy(sizePolicy)
        self.lbl_set.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_set.setObjectName("lbl_set")
        self.rightBox.addWidget(self.lbl_set)
        self.lay_select = QtWidgets.QHBoxLayout()
        self.lay_select.setObjectName("lay_select")
        self.btn_startselect = QtWidgets.QPushButton(wid_addcomp)
        self.btn_startselect.setObjectName("btn_startselect")
        self.lay_select.addWidget(self.btn_startselect)
        self.btn_selectall = QtWidgets.QPushButton(wid_addcomp)
        self.btn_selectall.setObjectName("btn_selectall")
        self.lay_select.addWidget(self.btn_selectall)
        self.rightBox.addLayout(self.lay_select)
        self.lay_material = QtWidgets.QHBoxLayout()
        self.lay_material.setObjectName("lay_material")
        self.lbl_material = QtWidgets.QLabel(wid_addcomp)
        self.lbl_material.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_material.sizePolicy().hasHeightForWidth())
        self.lbl_material.setSizePolicy(sizePolicy)
        self.lbl_material.setObjectName("lbl_material")
        self.lay_material.addWidget(self.lbl_material)
        self.cmb_material = QtWidgets.QComboBox(wid_addcomp)
        self.cmb_material.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_material.sizePolicy().hasHeightForWidth())
        self.cmb_material.setSizePolicy(sizePolicy)
        self.cmb_material.setMinimumSize(QtCore.QSize(130, 0))
        self.cmb_material.setObjectName("cmb_material")
        self.lay_material.addWidget(self.cmb_material)
        self.rightBox.addLayout(self.lay_material)
        self.lay_thickness = QtWidgets.QHBoxLayout()
        self.lay_thickness.setObjectName("lay_thickness")
        self.lbl_thickness = QtWidgets.QLabel(wid_addcomp)
        self.lbl_thickness.setEnabled(True)
        self.lbl_thickness.setObjectName("lbl_thickness")
        self.lay_thickness.addWidget(self.lbl_thickness)
        self.ln_thickness = QtWidgets.QLineEdit(wid_addcomp)
        self.ln_thickness.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_thickness.sizePolicy().hasHeightForWidth())
        self.ln_thickness.setSizePolicy(sizePolicy)
        self.ln_thickness.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_thickness.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_thickness.setObjectName("ln_thickness")
        self.lay_thickness.addWidget(self.ln_thickness)
        self.rightBox.addLayout(self.lay_thickness)
        self.btn_set = QtWidgets.QPushButton(wid_addcomp)
        self.btn_set.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_set.sizePolicy().hasHeightForWidth())
        self.btn_set.setSizePolicy(sizePolicy)
        self.btn_set.setObjectName("btn_set")
        self.rightBox.addWidget(self.btn_set)
        self.line_2 = QtWidgets.QFrame(wid_addcomp)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.rightBox.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(wid_addcomp)
        self.label_2.setEnabled(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.rightBox.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(wid_addcomp)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ln_remesh = QtWidgets.QLineEdit(wid_addcomp)
        self.ln_remesh.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_remesh.sizePolicy().hasHeightForWidth())
        self.ln_remesh.setSizePolicy(sizePolicy)
        self.ln_remesh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_remesh.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_remesh.setObjectName("ln_remesh")
        self.horizontalLayout_2.addWidget(self.ln_remesh)
        self.rightBox.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_remesh = QtWidgets.QPushButton(wid_addcomp)
        self.btn_remesh.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/TBicons/ico/clock.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_remesh.setIcon(icon)
        self.btn_remesh.setObjectName("btn_remesh")
        self.horizontalLayout_3.addWidget(self.btn_remesh)
        self.rightBox.addLayout(self.horizontalLayout_3)
        self.line_5 = QtWidgets.QFrame(wid_addcomp)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.rightBox.addWidget(self.line_5)
        self.label_4 = QtWidgets.QLabel(wid_addcomp)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.rightBox.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(wid_addcomp)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.ln_scale = QtWidgets.QLineEdit(wid_addcomp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_scale.sizePolicy().hasHeightForWidth())
        self.ln_scale.setSizePolicy(sizePolicy)
        self.ln_scale.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_scale.setObjectName("ln_scale")
        self.horizontalLayout_4.addWidget(self.ln_scale)
        self.rightBox.addLayout(self.horizontalLayout_4)
        self.btn_scale = QtWidgets.QPushButton(wid_addcomp)
        self.btn_scale.setObjectName("btn_scale")
        self.rightBox.addWidget(self.btn_scale)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightBox.addItem(spacerItem)
        self.line_3 = QtWidgets.QFrame(wid_addcomp)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.rightBox.addWidget(self.line_3)
        self.lay_btns = QtWidgets.QHBoxLayout()
        self.lay_btns.setObjectName("lay_btns")
        self.btn_ok = QtWidgets.QPushButton(wid_addcomp)
        self.btn_ok.setAutoDefault(True)
        self.btn_ok.setDefault(False)
        self.btn_ok.setObjectName("btn_ok")
        self.lay_btns.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(wid_addcomp)
        self.btn_cancel.setObjectName("btn_cancel")
        self.lay_btns.addWidget(self.btn_cancel)
        self.rightBox.addLayout(self.lay_btns)
        self.horizontalLayout.addLayout(self.rightBox)

        self.retranslateUi(wid_addcomp)
        QtCore.QMetaObject.connectSlotsByName(wid_addcomp)

    def retranslateUi(self, wid_addcomp):
        _translate = QtCore.QCoreApplication.translate
        wid_addcomp.setWindowTitle(_translate("wid_addcomp", "New component"))
        item = self.tbl_facestable.horizontalHeaderItem(0)
        item.setText(_translate("wid_addcomp", "Plane #"))
        item = self.tbl_facestable.horizontalHeaderItem(1)
        item.setText(_translate("wid_addcomp", "Thickness"))
        item = self.tbl_facestable.horizontalHeaderItem(2)
        item.setText(_translate("wid_addcomp", "Material"))
        self.lbl_gl.setText(_translate("wid_addcomp", "Component preview"))
        self.lbl_name.setText(_translate("wid_addcomp", "Component name:"))
        self.ln_name.setText(_translate("wid_addcomp", "Part"))
        self.label_5.setText(_translate("wid_addcomp", "Category name:"))
        self.ln_cat.setText(_translate("wid_addcomp", "Main"))
        self.lbl_set.setText(_translate("wid_addcomp", "Set thickness and material"))
        self.btn_startselect.setText(_translate("wid_addcomp", "Select planes"))
        self.btn_selectall.setText(_translate("wid_addcomp", "Select All"))
        self.lbl_material.setText(_translate("wid_addcomp", "Material:"))
        self.lbl_thickness.setText(_translate("wid_addcomp", "Thickness, mm:"))
        self.ln_thickness.setText(_translate("wid_addcomp", "0"))
        self.btn_set.setText(_translate("wid_addcomp", "Apply"))
        self.label_2.setText(_translate("wid_addcomp", "Remeshing: Join faces"))
        self.label.setText(_translate("wid_addcomp", "Max offset distance:"))
        self.ln_remesh.setText(_translate("wid_addcomp", "0.01"))
        self.btn_remesh.setText(_translate("wid_addcomp", "Apply remeshing"))
        self.label_4.setText(_translate("wid_addcomp", "Component scale "))
        self.label_3.setText(_translate("wid_addcomp", "Scale factor:"))
        self.ln_scale.setText(_translate("wid_addcomp", "1"))
        self.btn_scale.setText(_translate("wid_addcomp", "Apply scaling"))
        self.btn_ok.setText(_translate("wid_addcomp", "OK"))
        self.btn_cancel.setText(_translate("wid_addcomp", "Cancel"))


#import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wid_addcomp = QtWidgets.QWidget()
    ui = Ui_wid_addcomp()
    ui.setupUi(wid_addcomp)
    wid_addcomp.show()
    sys.exit(app.exec_())
