# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cnst.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 483)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tre_manager = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tre_manager.sizePolicy().hasHeightForWidth())
        self.tre_manager.setSizePolicy(sizePolicy)
        self.tre_manager.setMaximumSize(QtCore.QSize(160, 16777215))
        self.tre_manager.setFrameShape(QtWidgets.QFrame.Box)
        self.tre_manager.setObjectName("tre_manager")
        self.tre_manager.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.tre_manager)
        self.glbox = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glbox.sizePolicy().hasHeightForWidth())
        self.glbox.setSizePolicy(sizePolicy)
        self.glbox.setMinimumSize(QtCore.QSize(200, 0))
        self.glbox.setObjectName("glbox")
        self.horizontalLayout.addWidget(self.glbox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuViews = QtWidgets.QMenu(self.menuView)
        self.menuViews.setObjectName("menuViews")
        self.menuComponents = QtWidgets.QMenu(self.menubar)
        self.menuComponents.setGeometry(QtCore.QRect(236, 103, 184, 115))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuComponents.sizePolicy().hasHeightForWidth())
        self.menuComponents.setSizePolicy(sizePolicy)
        self.menuComponents.setMinimumSize(QtCore.QSize(150, 0))
        self.menuComponents.setObjectName("menuComponents")
        self.menuAddcomp = QtWidgets.QMenu(self.menuComponents)
        self.menuAddcomp.setGeometry(QtCore.QRect(419, 103, 210, 92))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuAddcomp.sizePolicy().hasHeightForWidth())
        self.menuAddcomp.setSizePolicy(sizePolicy)
        self.menuAddcomp.setMinimumSize(QtCore.QSize(0, 0))
        self.menuAddcomp.setObjectName("menuAddcomp")
        self.menuModify = QtWidgets.QMenu(self.menubar)
        self.menuModify.setObjectName("menuModify")
        self.menuMove = QtWidgets.QMenu(self.menuModify)
        self.menuMove.setObjectName("menuMove")
        self.menuStatistics = QtWidgets.QMenu(self.menubar)
        self.menuStatistics.setObjectName("menuStatistics")
        MainWindow.setMenuBar(self.menubar)
        self.actionfSaveas = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/TBicons/folder_full_accept.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfSaveas.setIcon(icon)
        self.actionfSaveas.setObjectName("actionfSaveas")
        self.actionfExport = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/TBicons/application_next.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfExport.setIcon(icon1)
        self.actionfExport.setObjectName("actionfExport")
        self.actionFront = QtWidgets.QAction(MainWindow)
        self.actionFront.setObjectName("actionFront")
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName("actionBack")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtWidgets.QAction(MainWindow)
        self.actionRight.setObjectName("actionRight")
        self.actionTop = QtWidgets.QAction(MainWindow)
        self.actionTop.setObjectName("actionTop")
        self.actionBottom = QtWidgets.QAction(MainWindow)
        self.actionBottom.setObjectName("actionBottom")
        self.actionSolid = QtWidgets.QAction(MainWindow)
        self.actionSolid.setObjectName("actionSolid")
        self.actionWireframe = QtWidgets.QAction(MainWindow)
        self.actionWireframe.setObjectName("actionWireframe")
        self.actionLighting = QtWidgets.QAction(MainWindow)
        self.actionLighting.setCheckable(True)
        self.actionLighting.setObjectName("actionLighting")
        self.actionBasecomp = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/TBicons/page_add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBasecomp.setIcon(icon2)
        self.actionBasecomp.setObjectName("actionBasecomp")
        self.actionArrays = QtWidgets.QAction(MainWindow)
        self.actionArrays.setObjectName("actionArrays")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionERA = QtWidgets.QAction(MainWindow)
        self.actionERA.setObjectName("actionERA")
        self.action_Constrain = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/TBicons/page_swap.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Constrain.setIcon(icon3)
        self.action_Constrain.setObjectName("action_Constrain")
        self.actionManage = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/TBicons/database_process.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManage.setIcon(icon4)
        self.actionManage.setObjectName("actionManage")
        self.actionfOpen = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/TBicons/folder_full.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfOpen.setIcon(icon5)
        self.actionfOpen.setObjectName("actionfOpen")
        self.actionfClose = QtWidgets.QAction(MainWindow)
        self.actionfClose.setObjectName("actionfClose")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/TBicons/note_edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon6)
        self.actionEdit.setObjectName("actionEdit")
        self.actionDeletecomp = QtWidgets.QAction(MainWindow)
        self.actionDeletecomp.setObjectName("actionDeletecomp")
        self.actionOpencomp = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/TBicons/page_up.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpencomp.setIcon(icon7)
        self.actionOpencomp.setObjectName("actionOpencomp")
        self.actionSavecomp = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/TBicons/page_down.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSavecomp.setIcon(icon8)
        self.actionSavecomp.setObjectName("actionSavecomp")
        self.actionSavematdb = QtWidgets.QAction(MainWindow)
        self.actionSavematdb.setObjectName("actionSavematdb")
        self.actionLoadmatdb = QtWidgets.QAction(MainWindow)
        self.actionLoadmatdb.setObjectName("actionLoadmatdb")
        self.actionHomo = QtWidgets.QAction(MainWindow)
        self.actionHomo.setObjectName("actionHomo")
        self.actionHetero = QtWidgets.QAction(MainWindow)
        self.actionHetero.setObjectName("actionHetero")
        self.actionColor = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/TBicons/process.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon9)
        self.actionColor.setObjectName("actionColor")
        self.actionShooting = QtWidgets.QAction(MainWindow)
        self.actionShooting.setObjectName("actionShooting")
        self.actionSlat_Armor = QtWidgets.QAction(MainWindow)
        self.actionSlat_Armor.setObjectName("actionSlat_Armor")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/TBicons/ico/blog_post.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon10)
        self.actionNew.setObjectName("actionNew")
        self.actionAssembly = QtWidgets.QAction(MainWindow)
        self.actionAssembly.setObjectName("actionAssembly")
        self.actionShapes_generator = QtWidgets.QAction(MainWindow)
        self.actionShapes_generator.setObjectName("actionShapes_generator")
        self.actionExtract_Revolve = QtWidgets.QAction(MainWindow)
        self.actionExtract_Revolve.setObjectName("actionExtract_Revolve")
        self.actionMirror = QtWidgets.QAction(MainWindow)
        self.actionMirror.setObjectName("actionMirror")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setEnabled(False)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionOrbital_shooting = QtWidgets.QAction(MainWindow)
        self.actionOrbital_shooting.setObjectName("actionOrbital_shooting")
        self.actionFunctional_scheme = QtWidgets.QAction(MainWindow)
        self.actionFunctional_scheme.setEnabled(False)
        self.actionFunctional_scheme.setObjectName("actionFunctional_scheme")
        self.actionArmor_th = QtWidgets.QAction(MainWindow)
        self.actionArmor_th.setCheckable(True)
        self.actionArmor_th.setObjectName("actionArmor_th")
        self.actionSingle_shots = QtWidgets.QAction(MainWindow)
        self.actionSingle_shots.setObjectName("actionSingle_shots")
        self.actionAxial_FF = QtWidgets.QAction(MainWindow)
        self.actionAxial_FF.setObjectName("actionAxial_FF")
        self.actionTestop1 = QtWidgets.QAction(MainWindow)
        self.actionTestop1.setObjectName("actionTestop1")
        self.actionTestop2 = QtWidgets.QAction(MainWindow)
        self.actionTestop2.setObjectName("actionTestop2")
        self.actionFree_roaming = QtWidgets.QAction(MainWindow)
        self.actionFree_roaming.setObjectName("actionFree_roaming")
        self.actionSet_on_coord = QtWidgets.QAction(MainWindow)
        self.actionSet_on_coord.setEnabled(False)
        self.actionSet_on_coord.setObjectName("actionSet_on_coord")
        self.actionDirectional_shooting = QtWidgets.QAction(MainWindow)
        self.actionDirectional_shooting.setObjectName("actionDirectional_shooting")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionfOpen)
        self.menuFile.addAction(self.actionfSaveas)
        self.menuFile.addAction(self.actionfExport)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionfClose)
        self.menuViews.addAction(self.actionFront)
        self.menuViews.addAction(self.actionBack)
        self.menuViews.addAction(self.actionLeft)
        self.menuViews.addAction(self.actionRight)
        self.menuViews.addAction(self.actionTop)
        self.menuViews.addAction(self.actionBottom)
        self.menuView.addAction(self.menuViews.menuAction())
        self.menuView.addAction(self.actionArmor_th)
        self.menuView.addAction(self.actionColor)
        self.menuAddcomp.addAction(self.actionOpencomp)
        self.menuAddcomp.addAction(self.actionBasecomp)
        self.menuComponents.addAction(self.menuAddcomp.menuAction())
        self.menuComponents.addAction(self.actionDeletecomp)
        self.menuComponents.addAction(self.actionSavecomp)
        self.menuMove.addAction(self.actionFree_roaming)
        self.menuMove.addAction(self.actionSet_on_coord)
        self.menuModify.addAction(self.actionEdit)
        self.menuModify.addAction(self.menuMove.menuAction())
        self.menuModify.addAction(self.action_Constrain)
        self.menuModify.addAction(self.actionArrays)
        self.menuStatistics.addAction(self.actionDirectional_shooting)
        self.menuStatistics.addAction(self.actionOrbital_shooting)
        self.menuStatistics.addAction(self.actionFunctional_scheme)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComponents.menuAction())
        self.menubar.addAction(self.menuModify.menuAction())
        self.menubar.addAction(self.menuStatistics.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Constructor"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.menuComponents.setTitle(_translate("MainWindow", "&Components"))
        self.menuAddcomp.setTitle(_translate("MainWindow", "&Add"))
        self.menuModify.setTitle(_translate("MainWindow", "&Modify"))
        self.menuMove.setTitle(_translate("MainWindow", "Move..."))
        self.menuStatistics.setTitle(_translate("MainWindow", "Statistics"))
        self.actionfSaveas.setText(_translate("MainWindow", "Save as..."))
        self.actionfExport.setText(_translate("MainWindow", "Export..."))
        self.actionFront.setText(_translate("MainWindow", "Front"))
        self.actionBack.setText(_translate("MainWindow", "Back"))
        self.actionLeft.setText(_translate("MainWindow", "Left"))
        self.actionRight.setText(_translate("MainWindow", "Right"))
        self.actionTop.setText(_translate("MainWindow", "Top"))
        self.actionBottom.setText(_translate("MainWindow", "Bottom"))
        self.actionSolid.setText(_translate("MainWindow", "Solid"))
        self.actionWireframe.setText(_translate("MainWindow", "Wireframe"))
        self.actionLighting.setText(_translate("MainWindow", "Lighting"))
        self.actionBasecomp.setText(_translate("MainWindow", "&Base component..."))
        self.actionArrays.setText(_translate("MainWindow", "Arrays..."))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionERA.setText(_translate("MainWindow", "Explosive Reaction Armor "))
        self.action_Constrain.setText(_translate("MainWindow", "Co&nstrain..."))
        self.actionManage.setText(_translate("MainWindow", "Manage..."))
        self.actionfOpen.setText(_translate("MainWindow", "Open..."))
        self.actionfClose.setText(_translate("MainWindow", "Close"))
        self.actionEdit.setText(_translate("MainWindow", "Edit..."))
        self.actionDeletecomp.setText(_translate("MainWindow", "Delete..."))
        self.actionOpencomp.setText(_translate("MainWindow", "Load..."))
        self.actionSavecomp.setText(_translate("MainWindow", "Save as..."))
        self.actionSavematdb.setText(_translate("MainWindow", "Save..."))
        self.actionLoadmatdb.setText(_translate("MainWindow", "Load..."))
        self.actionHomo.setText(_translate("MainWindow", "Homogeneous..."))
        self.actionHetero.setText(_translate("MainWindow", "Heterogeneous..."))
        self.actionColor.setText(_translate("MainWindow", "Color..."))
        self.actionShooting.setText(_translate("MainWindow", "Shooting"))
        self.actionSlat_Armor.setText(_translate("MainWindow", "Slat Armor"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionAssembly.setText(_translate("MainWindow", "Assembly"))
        self.actionShapes_generator.setText(_translate("MainWindow", "Shapes generator"))
        self.actionExtract_Revolve.setText(_translate("MainWindow", "Extract/Revolve"))
        self.actionMirror.setText(_translate("MainWindow", "Mirror..."))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionOrbital_shooting.setText(_translate("MainWindow", "Orbital shooting"))
        self.actionFunctional_scheme.setText(_translate("MainWindow", "Functional scheme..."))
        self.actionArmor_th.setText(_translate("MainWindow", "Armor th."))
        self.actionSingle_shots.setText(_translate("MainWindow", "Single shots"))
        self.actionAxial_FF.setText(_translate("MainWindow", "Axial FF"))
        self.actionTestop1.setText(_translate("MainWindow", "testop1"))
        self.actionTestop2.setText(_translate("MainWindow", "testop2"))
        self.actionFree_roaming.setText(_translate("MainWindow", "Free moving"))
        self.actionSet_on_coord.setText(_translate("MainWindow", "Set on coord."))
        self.actionDirectional_shooting.setText(_translate("MainWindow", "Directional shooting"))


#import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
