# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statsshow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 772)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_graph = QtWidgets.QTabWidget(Form)
        self.tab_graph.setObjectName("tab_graph")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tab_graph.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_graph.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ln_power = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_power.sizePolicy().hasHeightForWidth())
        self.ln_power.setSizePolicy(sizePolicy)
        self.ln_power.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_power.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_power.setObjectName("ln_power")
        self.horizontalLayout_3.addWidget(self.ln_power)
        self.btn_power = QtWidgets.QPushButton(self.tab_3)
        self.btn_power.setObjectName("btn_power")
        self.horizontalLayout_3.addWidget(self.btn_power)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tab_graph.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tab_graph)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tbl_res = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_res.sizePolicy().hasHeightForWidth())
        self.tbl_res.setSizePolicy(sizePolicy)
        self.tbl_res.setMinimumSize(QtCore.QSize(200, 150))
        self.tbl_res.setObjectName("tbl_res")
        self.tbl_res.setColumnCount(10)
        self.tbl_res.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_res.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.tbl_res)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.ln_angle2 = QtWidgets.QLineEdit(Form)
        self.ln_angle2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_angle2.sizePolicy().hasHeightForWidth())
        self.ln_angle2.setSizePolicy(sizePolicy)
        self.ln_angle2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_angle2.setObjectName("ln_angle2")
        self.gridLayout_14.addWidget(self.ln_angle2, 0, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_14.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_14.addWidget(self.label_31, 0, 3, 1, 1)
        self.ln_angle1 = QtWidgets.QLineEdit(Form)
        self.ln_angle1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_angle1.sizePolicy().hasHeightForWidth())
        self.ln_angle1.setSizePolicy(sizePolicy)
        self.ln_angle1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_angle1.setObjectName("ln_angle1")
        self.gridLayout_14.addWidget(self.ln_angle1, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_14)
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 1, 1, 1)
        self.tab_prx = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_prx.sizePolicy().hasHeightForWidth())
        self.tab_prx.setSizePolicy(sizePolicy)
        self.tab_prx.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tab_prx.setDocumentMode(True)
        self.tab_prx.setObjectName("tab_prx")
        self.tab_normalx = QtWidgets.QWidget()
        self.tab_normalx.setObjectName("tab_normalx")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_normalx)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_normalx)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.ln_xnrsigma = QtWidgets.QLineEdit(self.tab_normalx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_xnrsigma.sizePolicy().hasHeightForWidth())
        self.ln_xnrsigma.setSizePolicy(sizePolicy)
        self.ln_xnrsigma.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_xnrsigma.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_xnrsigma.setObjectName("ln_xnrsigma")
        self.gridLayout.addWidget(self.ln_xnrsigma, 1, 2, 1, 1)
        self.ln_xnrmu = QtWidgets.QLineEdit(self.tab_normalx)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_xnrmu.sizePolicy().hasHeightForWidth())
        self.ln_xnrmu.setSizePolicy(sizePolicy)
        self.ln_xnrmu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_xnrmu.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_xnrmu.setObjectName("ln_xnrmu")
        self.gridLayout.addWidget(self.ln_xnrmu, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_normalx)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.tab_prx.addTab(self.tab_normalx, "")
        self.tab_unix = QtWidgets.QWidget()
        self.tab_unix.setObjectName("tab_unix")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_unix)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ln_unixlow = QtWidgets.QLineEdit(self.tab_unix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_unixlow.sizePolicy().hasHeightForWidth())
        self.ln_unixlow.setSizePolicy(sizePolicy)
        self.ln_unixlow.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_unixlow.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_unixlow.setObjectName("ln_unixlow")
        self.gridLayout_2.addWidget(self.ln_unixlow, 0, 2, 1, 1)
        self.ln_unixhigh = QtWidgets.QLineEdit(self.tab_unix)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_unixhigh.sizePolicy().hasHeightForWidth())
        self.ln_unixhigh.setSizePolicy(sizePolicy)
        self.ln_unixhigh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_unixhigh.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_unixhigh.setObjectName("ln_unixhigh")
        self.gridLayout_2.addWidget(self.ln_unixhigh, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_unix)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_unix)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_unix, "")
        self.tab_students = QtWidgets.QWidget()
        self.tab_students.setObjectName("tab_students")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_students)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ln_stk = QtWidgets.QLineEdit(self.tab_students)
        self.ln_stk.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_stk.setObjectName("ln_stk")
        self.gridLayout_5.addWidget(self.ln_stk, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_students)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_students, "")
        self.tab_exp = QtWidgets.QWidget()
        self.tab_exp.setObjectName("tab_exp")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_exp)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ln_explambda = QtWidgets.QLineEdit(self.tab_exp)
        self.ln_explambda.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_explambda.setObjectName("ln_explambda")
        self.gridLayout_6.addWidget(self.ln_explambda, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_exp)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_exp, "")
        self.tab_lognorm = QtWidgets.QWidget()
        self.tab_lognorm.setObjectName("tab_lognorm")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_lognorm)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ln_logsigma = QtWidgets.QLineEdit(self.tab_lognorm)
        self.ln_logsigma.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_logsigma.setObjectName("ln_logsigma")
        self.gridLayout_7.addWidget(self.ln_logsigma, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_lognorm)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_lognorm)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 1, 1, 1)
        self.ln_logmu = QtWidgets.QLineEdit(self.tab_lognorm)
        self.ln_logmu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_logmu.setObjectName("ln_logmu")
        self.gridLayout_7.addWidget(self.ln_logmu, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 1, 0, 1, 1)
        self.tab_prx.addTab(self.tab_lognorm, "")
        self.tab_x2 = QtWidgets.QWidget()
        self.tab_x2.setObjectName("tab_x2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_x2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_19 = QtWidgets.QLabel(self.tab_x2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 1, 1, 1)
        self.ln_xk = QtWidgets.QLineEdit(self.tab_x2)
        self.ln_xk.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_xk.setObjectName("ln_xk")
        self.gridLayout_8.addWidget(self.ln_xk, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_x2, "")
        self.tab_beta = QtWidgets.QWidget()
        self.tab_beta.setObjectName("tab_beta")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_beta)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_20 = QtWidgets.QLabel(self.tab_beta)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_beta)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 1, 1, 1, 1)
        self.ln_betabeta = QtWidgets.QLineEdit(self.tab_beta)
        self.ln_betabeta.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_betabeta.setObjectName("ln_betabeta")
        self.gridLayout_9.addWidget(self.ln_betabeta, 1, 2, 1, 1)
        self.ln_betaalpha = QtWidgets.QLineEdit(self.tab_beta)
        self.ln_betaalpha.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_betaalpha.setObjectName("ln_betaalpha")
        self.gridLayout_9.addWidget(self.ln_betaalpha, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_beta, "")
        self.tab_gamma = QtWidgets.QWidget()
        self.tab_gamma.setObjectName("tab_gamma")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_gamma)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_22 = QtWidgets.QLabel(self.tab_gamma)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_gamma)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 1, 1, 1, 1)
        self.ln_gammatheta = QtWidgets.QLineEdit(self.tab_gamma)
        self.ln_gammatheta.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_gammatheta.setObjectName("ln_gammatheta")
        self.gridLayout_10.addWidget(self.ln_gammatheta, 0, 2, 1, 1)
        self.ln_gammak = QtWidgets.QLineEdit(self.tab_gamma)
        self.ln_gammak.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_gammak.setObjectName("ln_gammak")
        self.gridLayout_10.addWidget(self.ln_gammak, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem9, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_gamma, "")
        self.tab_weibull = QtWidgets.QWidget()
        self.tab_weibull.setObjectName("tab_weibull")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_weibull)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.ln_weilambda = QtWidgets.QLineEdit(self.tab_weibull)
        self.ln_weilambda.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_weilambda.setObjectName("ln_weilambda")
        self.gridLayout_11.addWidget(self.ln_weilambda, 0, 2, 1, 1)
        self.ln_weik = QtWidgets.QLineEdit(self.tab_weibull)
        self.ln_weik.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_weik.setObjectName("ln_weik")
        self.gridLayout_11.addWidget(self.ln_weik, 1, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_weibull)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_weibull)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_weibull, "")
        self.tab_custom = QtWidgets.QWidget()
        self.tab_custom.setObjectName("tab_custom")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_custom)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_26 = QtWidgets.QLabel(self.tab_custom)
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 0, 1, 1, 1)
        self.btn_custom = QtWidgets.QToolButton(self.tab_custom)
        self.btn_custom.setObjectName("btn_custom")
        self.gridLayout_12.addWidget(self.btn_custom, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem11, 0, 0, 1, 1)
        self.tab_prx.addTab(self.tab_custom, "")
        self.gridLayout_4.addWidget(self.tab_prx, 0, 1, 1, 1)
        self.tab_pry = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_pry.sizePolicy().hasHeightForWidth())
        self.tab_pry.setSizePolicy(sizePolicy)
        self.tab_pry.setMaximumSize(QtCore.QSize(9000, 16777215))
        self.tab_pry.setDocumentMode(True)
        self.tab_pry.setObjectName("tab_pry")
        self.tab_normaly = QtWidgets.QWidget()
        self.tab_normaly.setObjectName("tab_normaly")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tab_normaly)
        self.gridLayout_30.setObjectName("gridLayout_30")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem12, 0, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_normaly)
        self.label_51.setObjectName("label_51")
        self.gridLayout_30.addWidget(self.label_51, 0, 1, 1, 1)
        self.ln_ynrsigma = QtWidgets.QLineEdit(self.tab_normaly)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_ynrsigma.sizePolicy().hasHeightForWidth())
        self.ln_ynrsigma.setSizePolicy(sizePolicy)
        self.ln_ynrsigma.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_ynrsigma.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_ynrsigma.setObjectName("ln_ynrsigma")
        self.gridLayout_30.addWidget(self.ln_ynrsigma, 1, 2, 1, 1)
        self.ln_ynrmu = QtWidgets.QLineEdit(self.tab_normaly)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_ynrmu.sizePolicy().hasHeightForWidth())
        self.ln_ynrmu.setSizePolicy(sizePolicy)
        self.ln_ynrmu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_ynrmu.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_ynrmu.setObjectName("ln_ynrmu")
        self.gridLayout_30.addWidget(self.ln_ynrmu, 0, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_normaly)
        self.label_52.setObjectName("label_52")
        self.gridLayout_30.addWidget(self.label_52, 1, 1, 1, 1)
        self.tab_pry.addTab(self.tab_normaly, "")
        self.tab_uniy = QtWidgets.QWidget()
        self.tab_uniy.setObjectName("tab_uniy")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_uniy)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.tab_uniy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 1, 1, 1)
        self.ln_uniylow = QtWidgets.QLineEdit(self.tab_uniy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_uniylow.sizePolicy().hasHeightForWidth())
        self.ln_uniylow.setSizePolicy(sizePolicy)
        self.ln_uniylow.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_uniylow.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_uniylow.setObjectName("ln_uniylow")
        self.gridLayout_3.addWidget(self.ln_uniylow, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_uniy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 1, 1, 1)
        self.ln_uniyhigh = QtWidgets.QLineEdit(self.tab_uniy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_uniyhigh.sizePolicy().hasHeightForWidth())
        self.ln_uniyhigh.setSizePolicy(sizePolicy)
        self.ln_uniyhigh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_uniyhigh.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_uniyhigh.setObjectName("ln_uniyhigh")
        self.gridLayout_3.addWidget(self.ln_uniyhigh, 1, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_uniy, "")
        self.tab_students_4 = QtWidgets.QWidget()
        self.tab_students_4.setObjectName("tab_students_4")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.tab_students_4)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.ln_stk_4 = QtWidgets.QLineEdit(self.tab_students_4)
        self.ln_stk_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_stk_4.setObjectName("ln_stk_4")
        self.gridLayout_31.addWidget(self.ln_stk_4, 0, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_students_4)
        self.label_53.setObjectName("label_53")
        self.gridLayout_31.addWidget(self.label_53, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem14, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_students_4, "")
        self.tab_exp_4 = QtWidgets.QWidget()
        self.tab_exp_4.setObjectName("tab_exp_4")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.tab_exp_4)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.ln_explambda_4 = QtWidgets.QLineEdit(self.tab_exp_4)
        self.ln_explambda_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_explambda_4.setObjectName("ln_explambda_4")
        self.gridLayout_32.addWidget(self.ln_explambda_4, 0, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.tab_exp_4)
        self.label_54.setObjectName("label_54")
        self.gridLayout_32.addWidget(self.label_54, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem15, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_exp_4, "")
        self.tab_lognorm_4 = QtWidgets.QWidget()
        self.tab_lognorm_4.setObjectName("tab_lognorm_4")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.tab_lognorm_4)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.ln_logsigma_4 = QtWidgets.QLineEdit(self.tab_lognorm_4)
        self.ln_logsigma_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_logsigma_4.setObjectName("ln_logsigma_4")
        self.gridLayout_33.addWidget(self.ln_logsigma_4, 1, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_lognorm_4)
        self.label_55.setObjectName("label_55")
        self.gridLayout_33.addWidget(self.label_55, 1, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_lognorm_4)
        self.label_56.setObjectName("label_56")
        self.gridLayout_33.addWidget(self.label_56, 0, 1, 1, 1)
        self.ln_logmu_4 = QtWidgets.QLineEdit(self.tab_lognorm_4)
        self.ln_logmu_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_logmu_4.setObjectName("ln_logmu_4")
        self.gridLayout_33.addWidget(self.ln_logmu_4, 0, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem16, 1, 0, 1, 1)
        self.tab_pry.addTab(self.tab_lognorm_4, "")
        self.tab_x2_4 = QtWidgets.QWidget()
        self.tab_x2_4.setObjectName("tab_x2_4")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.tab_x2_4)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.label_57 = QtWidgets.QLabel(self.tab_x2_4)
        self.label_57.setObjectName("label_57")
        self.gridLayout_34.addWidget(self.label_57, 0, 1, 1, 1)
        self.ln_xk_4 = QtWidgets.QLineEdit(self.tab_x2_4)
        self.ln_xk_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_xk_4.setObjectName("ln_xk_4")
        self.gridLayout_34.addWidget(self.ln_xk_4, 0, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_34.addItem(spacerItem17, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_x2_4, "")
        self.tab_beta_4 = QtWidgets.QWidget()
        self.tab_beta_4.setObjectName("tab_beta_4")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.tab_beta_4)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_58 = QtWidgets.QLabel(self.tab_beta_4)
        self.label_58.setObjectName("label_58")
        self.gridLayout_35.addWidget(self.label_58, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_beta_4)
        self.label_59.setObjectName("label_59")
        self.gridLayout_35.addWidget(self.label_59, 1, 1, 1, 1)
        self.ln_betabeta_4 = QtWidgets.QLineEdit(self.tab_beta_4)
        self.ln_betabeta_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_betabeta_4.setObjectName("ln_betabeta_4")
        self.gridLayout_35.addWidget(self.ln_betabeta_4, 1, 2, 1, 1)
        self.ln_betaalpha_4 = QtWidgets.QLineEdit(self.tab_beta_4)
        self.ln_betaalpha_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_betaalpha_4.setObjectName("ln_betaalpha_4")
        self.gridLayout_35.addWidget(self.ln_betaalpha_4, 0, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem18, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_beta_4, "")
        self.tab_gamma_4 = QtWidgets.QWidget()
        self.tab_gamma_4.setObjectName("tab_gamma_4")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.tab_gamma_4)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label_60 = QtWidgets.QLabel(self.tab_gamma_4)
        self.label_60.setObjectName("label_60")
        self.gridLayout_36.addWidget(self.label_60, 0, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_gamma_4)
        self.label_61.setObjectName("label_61")
        self.gridLayout_36.addWidget(self.label_61, 1, 1, 1, 1)
        self.ln_gammatheta_4 = QtWidgets.QLineEdit(self.tab_gamma_4)
        self.ln_gammatheta_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_gammatheta_4.setObjectName("ln_gammatheta_4")
        self.gridLayout_36.addWidget(self.ln_gammatheta_4, 0, 2, 1, 1)
        self.ln_gammak_4 = QtWidgets.QLineEdit(self.tab_gamma_4)
        self.ln_gammak_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_gammak_4.setObjectName("ln_gammak_4")
        self.gridLayout_36.addWidget(self.ln_gammak_4, 1, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem19, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_gamma_4, "")
        self.tab_weibull_4 = QtWidgets.QWidget()
        self.tab_weibull_4.setObjectName("tab_weibull_4")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.tab_weibull_4)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.ln_weilambda_4 = QtWidgets.QLineEdit(self.tab_weibull_4)
        self.ln_weilambda_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_weilambda_4.setObjectName("ln_weilambda_4")
        self.gridLayout_37.addWidget(self.ln_weilambda_4, 0, 2, 1, 1)
        self.ln_weik_4 = QtWidgets.QLineEdit(self.tab_weibull_4)
        self.ln_weik_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_weik_4.setObjectName("ln_weik_4")
        self.gridLayout_37.addWidget(self.ln_weik_4, 1, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.tab_weibull_4)
        self.label_62.setObjectName("label_62")
        self.gridLayout_37.addWidget(self.label_62, 1, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.tab_weibull_4)
        self.label_63.setObjectName("label_63")
        self.gridLayout_37.addWidget(self.label_63, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem20, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_weibull_4, "")
        self.tab_custom_4 = QtWidgets.QWidget()
        self.tab_custom_4.setObjectName("tab_custom_4")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.tab_custom_4)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.label_64 = QtWidgets.QLabel(self.tab_custom_4)
        self.label_64.setObjectName("label_64")
        self.gridLayout_38.addWidget(self.label_64, 0, 1, 1, 1)
        self.btn_custom_4 = QtWidgets.QToolButton(self.tab_custom_4)
        self.btn_custom_4.setObjectName("btn_custom_4")
        self.gridLayout_38.addWidget(self.btn_custom_4, 0, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_38.addItem(spacerItem21, 0, 0, 1, 1)
        self.tab_pry.addTab(self.tab_custom_4, "")
        self.gridLayout_4.addWidget(self.tab_pry, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chb_fsv = QtWidgets.QCheckBox(Form)
        self.chb_fsv.setEnabled(False)
        self.chb_fsv.setObjectName("chb_fsv")
        self.horizontalLayout_6.addWidget(self.chb_fsv)
        self.cmb_fcv = QtWidgets.QComboBox(Form)
        self.cmb_fcv.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_fcv.sizePolicy().hasHeightForWidth())
        self.cmb_fcv.setSizePolicy(sizePolicy)
        self.cmb_fcv.setObjectName("cmb_fcv")
        self.horizontalLayout_6.addWidget(self.cmb_fcv)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rdb_regorbit = QtWidgets.QRadioButton(Form)
        self.rdb_regorbit.setEnabled(False)
        self.rdb_regorbit.setObjectName("rdb_regorbit")
        self.horizontalLayout_7.addWidget(self.rdb_regorbit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_9.addWidget(self.label_32)
        self.ln_regpoints = QtWidgets.QLineEdit(Form)
        self.ln_regpoints.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_regpoints.sizePolicy().hasHeightForWidth())
        self.ln_regpoints.setSizePolicy(sizePolicy)
        self.ln_regpoints.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_regpoints.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_regpoints.setObjectName("ln_regpoints")
        self.horizontalLayout_9.addWidget(self.ln_regpoints)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.rdb_degorbit = QtWidgets.QRadioButton(Form)
        self.rdb_degorbit.setChecked(True)
        self.rdb_degorbit.setObjectName("rdb_degorbit")
        self.verticalLayout_2.addWidget(self.rdb_degorbit)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 0, 3, 1, 1)
        self.ln_nastep = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_nastep.sizePolicy().hasHeightForWidth())
        self.ln_nastep.setSizePolicy(sizePolicy)
        self.ln_nastep.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_nastep.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_nastep.setObjectName("ln_nastep")
        self.gridLayout_13.addWidget(self.ln_nastep, 1, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_13.addWidget(self.label_16, 1, 0, 1, 1)
        self.ln_grang0 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_grang0.sizePolicy().hasHeightForWidth())
        self.ln_grang0.setSizePolicy(sizePolicy)
        self.ln_grang0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_grang0.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_grang0.setObjectName("ln_grang0")
        self.gridLayout_13.addWidget(self.ln_grang0, 0, 1, 1, 1)
        self.ln_gastep = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_gastep.sizePolicy().hasHeightForWidth())
        self.ln_gastep.setSizePolicy(sizePolicy)
        self.ln_gastep.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_gastep.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_gastep.setObjectName("ln_gastep")
        self.gridLayout_13.addWidget(self.ln_gastep, 0, 4, 1, 1)
        self.label_28 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 1, 3, 1, 1)
        self.ln_norang0 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_norang0.sizePolicy().hasHeightForWidth())
        self.ln_norang0.setSizePolicy(sizePolicy)
        self.ln_norang0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_norang0.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_norang0.setObjectName("ln_norang0")
        self.gridLayout_13.addWidget(self.ln_norang0, 1, 1, 1, 1)
        self.ln_grang1 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_grang1.sizePolicy().hasHeightForWidth())
        self.ln_grang1.setSizePolicy(sizePolicy)
        self.ln_grang1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_grang1.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_grang1.setObjectName("ln_grang1")
        self.gridLayout_13.addWidget(self.ln_grang1, 0, 2, 1, 1)
        self.ln_norang1 = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_norang1.sizePolicy().hasHeightForWidth())
        self.ln_norang1.setSizePolicy(sizePolicy)
        self.ln_norang1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ln_norang1.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_norang1.setObjectName("ln_norang1")
        self.gridLayout_13.addWidget(self.ln_norang1, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_13)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.ln_savefile = QtWidgets.QLineEdit(Form)
        self.ln_savefile.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_savefile.sizePolicy().hasHeightForWidth())
        self.ln_savefile.setSizePolicy(sizePolicy)
        self.ln_savefile.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ln_savefile.setObjectName("ln_savefile")
        self.horizontalLayout_5.addWidget(self.ln_savefile)
        self.tbtn_filepath = QtWidgets.QToolButton(Form)
        self.tbtn_filepath.setObjectName("tbtn_filepath")
        self.horizontalLayout_5.addWidget(self.tbtn_filepath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.btn_grid = QtWidgets.QPushButton(Form)
        self.btn_grid.setCheckable(True)
        self.btn_grid.setObjectName("btn_grid")
        self.verticalLayout_2.addWidget(self.btn_grid)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ln_n = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_n.sizePolicy().hasHeightForWidth())
        self.ln_n.setSizePolicy(sizePolicy)
        self.ln_n.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_n.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_n.setObjectName("ln_n")
        self.horizontalLayout_2.addWidget(self.ln_n)
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setAutoDefault(True)
        self.btn_start.setDefault(True)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tbl_tot = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_tot.sizePolicy().hasHeightForWidth())
        self.tbl_tot.setSizePolicy(sizePolicy)
        self.tbl_tot.setObjectName("tbl_tot")
        self.tbl_tot.setColumnCount(2)
        self.tbl_tot.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tot.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_tot.setHorizontalHeaderItem(1, item)
        self.tbl_tot.horizontalHeader().setDefaultSectionSize(130)
        self.verticalLayout_2.addWidget(self.tbl_tot)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        self.tab_graph.setCurrentIndex(0)
        self.tab_prx.setCurrentIndex(0)
        self.tab_pry.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Orbital shooting"))
        self.tab_graph.setTabText(self.tab_graph.indexOf(self.tab_1), _translate("Form", "Eq. Thickness"))
        self.tab_graph.setTabText(self.tab_graph.indexOf(self.tab_2), _translate("Form", "Plot 1"))
        self.ln_power.setText(_translate("Form", "500"))
        self.btn_power.setText(_translate("Form", "Power, mm"))
        self.tab_graph.setTabText(self.tab_graph.indexOf(self.tab_3), _translate("Form", "Plot 2"))
        self.label_2.setText(_translate("Form", "Shooting results"))
        item = self.tbl_res.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Direction #"))
        item = self.tbl_res.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Hit, %"))
        item = self.tbl_res.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Mean armor th."))
        item = self.tbl_res.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Type A, %"))
        item = self.tbl_res.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Type A, th"))
        item = self.tbl_res.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Type B, %"))
        item = self.tbl_res.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Type B, th"))
        item = self.tbl_res.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Type C, %"))
        item = self.tbl_res.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Type C, th"))
        item = self.tbl_res.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Point"))
        self.label_30.setText(_translate("Form", "Y angle"))
        self.label_31.setText(_translate("Form", "ZX angle"))
        self.label_18.setText(_translate("Form", "X axis:"))
        self.label_17.setText(_translate("Form", "Y axis:"))
        self.label_4.setText(_translate("Form", "Mu"))
        self.ln_xnrsigma.setText(_translate("Form", "100"))
        self.ln_xnrmu.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "Sigma"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_normalx), _translate("Form", "Normal"))
        self.ln_unixlow.setText(_translate("Form", "-300"))
        self.ln_unixhigh.setText(_translate("Form", "300"))
        self.label_13.setText(_translate("Form", "High"))
        self.label_12.setText(_translate("Form", "Low"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_unix), _translate("Form", "Uniform"))
        self.label_6.setText(_translate("Form", "k"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_students), _translate("Form", "Student\'s"))
        self.label_8.setText(_translate("Form", "Lambda"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_exp), _translate("Form", "Exponential"))
        self.label_10.setText(_translate("Form", "Sigma"))
        self.label_9.setText(_translate("Form", "Mu"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_lognorm), _translate("Form", "Log Normal"))
        self.label_19.setText(_translate("Form", "k"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_x2), _translate("Form", "Chi-squared"))
        self.label_20.setText(_translate("Form", "Alpha"))
        self.label_21.setText(_translate("Form", "Beta"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_beta), _translate("Form", "Beta"))
        self.label_22.setText(_translate("Form", "Theta"))
        self.label_23.setText(_translate("Form", "k"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_gamma), _translate("Form", "Gamma"))
        self.label_25.setText(_translate("Form", "k"))
        self.label_24.setText(_translate("Form", "Lambda"))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_weibull), _translate("Form", "Weibull"))
        self.label_26.setText(_translate("Form", "Load"))
        self.btn_custom.setText(_translate("Form", "..."))
        self.tab_prx.setTabText(self.tab_prx.indexOf(self.tab_custom), _translate("Form", "Custom"))
        self.label_51.setText(_translate("Form", "Mu"))
        self.ln_ynrsigma.setText(_translate("Form", "100"))
        self.ln_ynrmu.setText(_translate("Form", "0"))
        self.label_52.setText(_translate("Form", "Sigma"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_normaly), _translate("Form", "Normal"))
        self.label_14.setText(_translate("Form", "Low"))
        self.ln_uniylow.setText(_translate("Form", "-250"))
        self.label_15.setText(_translate("Form", "High"))
        self.ln_uniyhigh.setText(_translate("Form", "250"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_uniy), _translate("Form", "Uniform"))
        self.label_53.setText(_translate("Form", "k"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_students_4), _translate("Form", "Student\'s"))
        self.label_54.setText(_translate("Form", "Lambda"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_exp_4), _translate("Form", "Exponential"))
        self.label_55.setText(_translate("Form", "Sigma"))
        self.label_56.setText(_translate("Form", "Mu"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_lognorm_4), _translate("Form", "Log Normal"))
        self.label_57.setText(_translate("Form", "k"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_x2_4), _translate("Form", "Chi-squared"))
        self.label_58.setText(_translate("Form", "Alpha"))
        self.label_59.setText(_translate("Form", "Beta"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_beta_4), _translate("Form", "Beta"))
        self.label_60.setText(_translate("Form", "Theta"))
        self.label_61.setText(_translate("Form", "k"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_gamma_4), _translate("Form", "Gamma"))
        self.label_62.setText(_translate("Form", "k"))
        self.label_63.setText(_translate("Form", "Lambda"))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_weibull_4), _translate("Form", "Weibull"))
        self.label_64.setText(_translate("Form", "Load"))
        self.btn_custom_4.setText(_translate("Form", "..."))
        self.tab_pry.setTabText(self.tab_pry.indexOf(self.tab_custom_4), _translate("Form", "Custom"))
        self.chb_fsv.setText(_translate("Form", "Enable FSV analysis"))
        self.rdb_regorbit.setText(_translate("Form", "Orbit shootout, Fib. grid"))
        self.label_32.setText(_translate("Form", "Number of points :"))
        self.ln_regpoints.setText(_translate("Form", "5000"))
        self.rdb_degorbit.setText(_translate("Form", "Orbit shootout with angle-based grid"))
        self.label_3.setText(_translate("Form", "G. angle"))
        self.label_27.setText(_translate("Form", "Step"))
        self.ln_nastep.setText(_translate("Form", "5"))
        self.label_16.setText(_translate("Form", "N. angle"))
        self.ln_grang0.setText(_translate("Form", "0"))
        self.ln_gastep.setText(_translate("Form", "6"))
        self.label_28.setText(_translate("Form", "Step"))
        self.ln_norang0.setText(_translate("Form", "0"))
        self.ln_grang1.setText(_translate("Form", "360"))
        self.ln_norang1.setText(_translate("Form", "90"))
        self.checkBox.setText(_translate("Form", "Save results to"))
        self.tbtn_filepath.setText(_translate("Form", "..."))
        self.btn_grid.setText(_translate("Form", "Show grid"))
        self.label.setText(_translate("Form", "Shots:"))
        self.ln_n.setText(_translate("Form", "500"))
        self.btn_start.setText(_translate("Form", "Start"))
        item = self.tbl_tot.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Stat"))
        item = self.tbl_tot.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Res"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
