# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'move.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(181, 550)
        Form.setMinimumSize(QtCore.QSize(170, 550))
        Form.setMaximumSize(QtCore.QSize(278, 550))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.lst_comps = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_comps.sizePolicy().hasHeightForWidth())
        self.lst_comps.setSizePolicy(sizePolicy)
        self.lst_comps.setObjectName("lst_comps")
        self.verticalLayout.addWidget(self.lst_comps)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dsb_mz = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_mz.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_mz.setDecimals(1)
        self.dsb_mz.setObjectName("dsb_mz")
        self.gridLayout.addWidget(self.dsb_mz, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dsb_my = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_my.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_my.setDecimals(1)
        self.dsb_my.setObjectName("dsb_my")
        self.gridLayout.addWidget(self.dsb_my, 2, 1, 1, 1)
        self.dsb_mx = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_mx.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_mx.setDecimals(1)
        self.dsb_mx.setObjectName("dsb_mx")
        self.gridLayout.addWidget(self.dsb_mx, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.ln_movestep = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_movestep.sizePolicy().hasHeightForWidth())
        self.ln_movestep.setSizePolicy(sizePolicy)
        self.ln_movestep.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_movestep.setObjectName("ln_movestep")
        self.gridLayout.addWidget(self.ln_movestep, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dsb_rz = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_rz.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_rz.setDecimals(1)
        self.dsb_rz.setObjectName("dsb_rz")
        self.gridLayout_2.addWidget(self.dsb_rz, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.dsb_ry = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_ry.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_ry.setDecimals(1)
        self.dsb_ry.setObjectName("dsb_ry")
        self.gridLayout_2.addWidget(self.dsb_ry, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.dsb_rx = QtWidgets.QDoubleSpinBox(Form)
        self.dsb_rx.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_rx.setDecimals(1)
        self.dsb_rx.setObjectName("dsb_rx")
        self.gridLayout_2.addWidget(self.dsb_rx, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.ln_rotatestep = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_rotatestep.sizePolicy().hasHeightForWidth())
        self.ln_rotatestep.setSizePolicy(sizePolicy)
        self.ln_rotatestep.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_rotatestep.setObjectName("ln_rotatestep")
        self.gridLayout_2.addWidget(self.ln_rotatestep, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.btn_done = QtWidgets.QPushButton(Form)
        self.btn_done.setAutoDefault(True)
        self.btn_done.setDefault(True)
        self.btn_done.setObjectName("btn_done")
        self.verticalLayout.addWidget(self.btn_done)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Move"))
        self.label_11.setText(_translate("Form", "Select component"))
        self.label_4.setText(_translate("Form", "Move"))
        self.label_2.setText(_translate("Form", "Y"))
        self.label_3.setText(_translate("Form", "Z"))
        self.label.setText(_translate("Form", "X"))
        self.label_9.setText(_translate("Form", "Step"))
        self.ln_movestep.setText(_translate("Form", "50"))
        self.label_5.setText(_translate("Form", "Rotate"))
        self.label_8.setText(_translate("Form", "Z"))
        self.label_7.setText(_translate("Form", "Y"))
        self.label_6.setText(_translate("Form", "X"))
        self.label_10.setText(_translate("Form", "Step"))
        self.ln_rotatestep.setText(_translate("Form", "5"))
        self.btn_done.setText(_translate("Form", "Done"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
