# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addproj.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wid_addproj(object):
    def setupUi(self, wid_addproj):
        wid_addproj.setObjectName(_fromUtf8("wid_addproj"))
        wid_addproj.resize(950, 600)
        wid_addproj.setMinimumSize(QtCore.QSize(950, 0))
        self.horizontalLayout = QtGui.QHBoxLayout(wid_addproj)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tre_details = QtGui.QTreeWidget(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tre_details.sizePolicy().hasHeightForWidth())
        self.tre_details.setSizePolicy(sizePolicy)
        self.tre_details.setMinimumSize(QtCore.QSize(255, 0))
        self.tre_details.setMaximumSize(QtCore.QSize(255, 16777215))
        self.tre_details.setObjectName(_fromUtf8("tre_details"))
        self.tre_details.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.tre_details)
        self.tbl_points = QtGui.QTableWidget(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_points.sizePolicy().hasHeightForWidth())
        self.tbl_points.setSizePolicy(sizePolicy)
        self.tbl_points.setMinimumSize(QtCore.QSize(255, 0))
        self.tbl_points.setMaximumSize(QtCore.QSize(255, 16777215))
        self.tbl_points.setObjectName(_fromUtf8("tbl_points"))
        self.tbl_points.setColumnCount(2)
        self.tbl_points.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tbl_points.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tbl_points.setHorizontalHeaderItem(1, item)
        self.tbl_points.horizontalHeader().setDefaultSectionSize(110)
        self.verticalLayout.addWidget(self.tbl_points)
        self.label_7 = QtGui.QLabel(wid_addproj)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_adddetail = QtGui.QPushButton(wid_addproj)
        self.btn_adddetail.setObjectName(_fromUtf8("btn_adddetail"))
        self.horizontalLayout_5.addWidget(self.btn_adddetail)
        self.btn_deldetail = QtGui.QPushButton(wid_addproj)
        self.btn_deldetail.setObjectName(_fromUtf8("btn_deldetail"))
        self.horizontalLayout_5.addWidget(self.btn_deldetail)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.btn_rectangle = QtGui.QPushButton(wid_addproj)
        self.btn_rectangle.setObjectName(_fromUtf8("btn_rectangle"))
        self.horizontalLayout_9.addWidget(self.btn_rectangle)
        self.btn_dropcont = QtGui.QPushButton(wid_addproj)
        self.btn_dropcont.setObjectName(_fromUtf8("btn_dropcont"))
        self.horizontalLayout_9.addWidget(self.btn_dropcont)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.lay_gl = QtGui.QVBoxLayout()
        self.lay_gl.setObjectName(_fromUtf8("lay_gl"))
        self.lbl_gl = QtGui.QLabel(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_gl.sizePolicy().hasHeightForWidth())
        self.lbl_gl.setSizePolicy(sizePolicy)
        self.lbl_gl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gl.setObjectName(_fromUtf8("lbl_gl"))
        self.lay_gl.addWidget(self.lbl_gl)
        self.glbox = QtGui.QWidget(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glbox.sizePolicy().hasHeightForWidth())
        self.glbox.setSizePolicy(sizePolicy)
        self.glbox.setMinimumSize(QtCore.QSize(300, 300))
        self.glbox.setObjectName(_fromUtf8("glbox"))
        self.lay_gl.addWidget(self.glbox)
        self.horizontalLayout.addLayout(self.lay_gl)
        self.line_4 = QtGui.QFrame(wid_addproj)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.rightBox = QtGui.QVBoxLayout()
        self.rightBox.setObjectName(_fromUtf8("rightBox"))
        self.lay_name = QtGui.QHBoxLayout()
        self.lay_name.setObjectName(_fromUtf8("lay_name"))
        self.lbl_name = QtGui.QLabel(wid_addproj)
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.lay_name.addWidget(self.lbl_name)
        self.ln_name = QtGui.QLineEdit(wid_addproj)
        self.ln_name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_name.sizePolicy().hasHeightForWidth())
        self.ln_name.setSizePolicy(sizePolicy)
        self.ln_name.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ln_name.setObjectName(_fromUtf8("ln_name"))
        self.lay_name.addWidget(self.ln_name)
        self.rightBox.addLayout(self.lay_name)
        self.line = QtGui.QFrame(wid_addproj)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.rightBox.addWidget(self.line)
        self.label_2 = QtGui.QLabel(wid_addproj)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.rightBox.addWidget(self.label_2)
        self.tbl_params = QtGui.QTableWidget(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_params.sizePolicy().hasHeightForWidth())
        self.tbl_params.setSizePolicy(sizePolicy)
        self.tbl_params.setObjectName(_fromUtf8("tbl_params"))
        self.tbl_params.setColumnCount(2)
        self.tbl_params.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tbl_params.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tbl_params.setHorizontalHeaderItem(1, item)
        self.tbl_params.horizontalHeader().setDefaultSectionSize(120)
        self.rightBox.addWidget(self.tbl_params)
        self.label_8 = QtGui.QLabel(wid_addproj)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.rightBox.addWidget(self.label_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(wid_addproj)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.ln_angle = QtGui.QLineEdit(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_angle.sizePolicy().hasHeightForWidth())
        self.ln_angle.setSizePolicy(sizePolicy)
        self.ln_angle.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_angle.setObjectName(_fromUtf8("ln_angle"))
        self.horizontalLayout_3.addWidget(self.ln_angle)
        self.label_11 = QtGui.QLabel(wid_addproj)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_3.addWidget(self.label_11)
        self.ln_dy = QtGui.QLineEdit(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_dy.sizePolicy().hasHeightForWidth())
        self.ln_dy.setSizePolicy(sizePolicy)
        self.ln_dy.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_dy.setObjectName(_fromUtf8("ln_dy"))
        self.horizontalLayout_3.addWidget(self.ln_dy)
        self.rightBox.addLayout(self.horizontalLayout_3)
        self.line_5 = QtGui.QFrame(wid_addproj)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.rightBox.addWidget(self.line_5)
        self.lbl_set = QtGui.QLabel(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_set.sizePolicy().hasHeightForWidth())
        self.lbl_set.setSizePolicy(sizePolicy)
        self.lbl_set.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_set.setObjectName(_fromUtf8("lbl_set"))
        self.rightBox.addWidget(self.lbl_set)
        self.lay_material = QtGui.QHBoxLayout()
        self.lay_material.setObjectName(_fromUtf8("lay_material"))
        self.lbl_material = QtGui.QLabel(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_material.sizePolicy().hasHeightForWidth())
        self.lbl_material.setSizePolicy(sizePolicy)
        self.lbl_material.setObjectName(_fromUtf8("lbl_material"))
        self.lay_material.addWidget(self.lbl_material)
        self.cmb_material = QtGui.QComboBox(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_material.sizePolicy().hasHeightForWidth())
        self.cmb_material.setSizePolicy(sizePolicy)
        self.cmb_material.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_material.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cmb_material.setObjectName(_fromUtf8("cmb_material"))
        self.lay_material.addWidget(self.cmb_material)
        self.rightBox.addLayout(self.lay_material)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.btn_update = QtGui.QPushButton(wid_addproj)
        self.btn_update.setObjectName(_fromUtf8("btn_update"))
        self.horizontalLayout_8.addWidget(self.btn_update)
        self.btn_default = QtGui.QPushButton(wid_addproj)
        self.btn_default.setObjectName(_fromUtf8("btn_default"))
        self.horizontalLayout_8.addWidget(self.btn_default)
        self.rightBox.addLayout(self.horizontalLayout_8)
        self.label_12 = QtGui.QLabel(wid_addproj)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.rightBox.addWidget(self.label_12)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(wid_addproj)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        self.ln_remesh = QtGui.QLineEdit(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_remesh.sizePolicy().hasHeightForWidth())
        self.ln_remesh.setSizePolicy(sizePolicy)
        self.ln_remesh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ln_remesh.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_remesh.setObjectName(_fromUtf8("ln_remesh"))
        self.horizontalLayout_10.addWidget(self.ln_remesh)
        self.rightBox.addLayout(self.horizontalLayout_10)
        self.btn_remesh = QtGui.QPushButton(wid_addproj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remesh.sizePolicy().hasHeightForWidth())
        self.btn_remesh.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/TBicons/ico/clock.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_remesh.setIcon(icon)
        self.btn_remesh.setObjectName(_fromUtf8("btn_remesh"))
        self.rightBox.addWidget(self.btn_remesh)
        self.line_2 = QtGui.QFrame(wid_addproj)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.rightBox.addWidget(self.line_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.rightBox.addItem(spacerItem1)
        self.line_3 = QtGui.QFrame(wid_addproj)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.rightBox.addWidget(self.line_3)
        self.lay_btns = QtGui.QHBoxLayout()
        self.lay_btns.setObjectName(_fromUtf8("lay_btns"))
        self.btn_ok = QtGui.QPushButton(wid_addproj)
        self.btn_ok.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_ok.setDefault(True)
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.lay_btns.addWidget(self.btn_ok)
        self.btn_cancel = QtGui.QPushButton(wid_addproj)
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.lay_btns.addWidget(self.btn_cancel)
        self.rightBox.addLayout(self.lay_btns)
        self.horizontalLayout.addLayout(self.rightBox)

        self.retranslateUi(wid_addproj)
        QtCore.QMetaObject.connectSlotsByName(wid_addproj)

    def retranslateUi(self, wid_addproj):
        wid_addproj.setWindowTitle(_translate("wid_addproj", "Projectile Assembly", None))
        item = self.tbl_points.horizontalHeaderItem(0)
        item.setText(_translate("wid_addproj", "#Point", None))
        item = self.tbl_points.horizontalHeaderItem(1)
        item.setText(_translate("wid_addproj", "Connection", None))
        self.label_7.setText(_translate("wid_addproj", "Contour", None))
        self.btn_adddetail.setText(_translate("wid_addproj", "Add detail", None))
        self.btn_deldetail.setText(_translate("wid_addproj", "Delete detail", None))
        self.btn_rectangle.setText(_translate("wid_addproj", "Rectangle", None))
        self.btn_dropcont.setText(_translate("wid_addproj", "Drop contour", None))
        self.lbl_gl.setText(_translate("wid_addproj", "Component preview", None))
        self.lbl_name.setText(_translate("wid_addproj", "Detail name:", None))
        self.ln_name.setText(_translate("wid_addproj", "TESTNAME", None))
        self.label_2.setText(_translate("wid_addproj", "Detail parameters", None))
        item = self.tbl_params.horizontalHeaderItem(0)
        item.setText(_translate("wid_addproj", "Parameter", None))
        item = self.tbl_params.horizontalHeaderItem(1)
        item.setText(_translate("wid_addproj", "Value", None))
        self.label_8.setText(_translate("wid_addproj", "View parameters", None))
        self.label_10.setText(_translate("wid_addproj", "Angle", None))
        self.ln_angle.setText(_translate("wid_addproj", "180", None))
        self.label_11.setText(_translate("wid_addproj", "Y:", None))
        self.ln_dy.setText(_translate("wid_addproj", "40", None))
        self.lbl_set.setText(_translate("wid_addproj", "Material", None))
        self.lbl_material.setText(_translate("wid_addproj", "Material:", None))
        self.btn_update.setText(_translate("wid_addproj", "Update", None))
        self.btn_default.setText(_translate("wid_addproj", "Default", None))
        self.label_12.setText(_translate("wid_addproj", "Remeshing", None))
        self.label_13.setText(_translate("wid_addproj", "Offset distance parameter:", None))
        self.ln_remesh.setText(_translate("wid_addproj", "1e-2", None))
        self.btn_remesh.setText(_translate("wid_addproj", "Apply Remeshing", None))
        self.btn_ok.setText(_translate("wid_addproj", "OK", None))
        self.btn_cancel.setText(_translate("wid_addproj", "Cancel", None))

import res_rc
