# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cnst.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(824, 588)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tre_manager = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tre_manager.sizePolicy().hasHeightForWidth())
        self.tre_manager.setSizePolicy(sizePolicy)
        self.tre_manager.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tre_manager.setFrameShape(QtGui.QFrame.Box)
        self.tre_manager.setObjectName(_fromUtf8("tre_manager"))
        self.tre_manager.headerItem().setText(0, _fromUtf8("1"))
        self.horizontalLayout.addWidget(self.tre_manager)
        self.glbox = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glbox.sizePolicy().hasHeightForWidth())
        self.glbox.setSizePolicy(sizePolicy)
        self.glbox.setMinimumSize(QtCore.QSize(200, 0))
        self.glbox.setObjectName(_fromUtf8("glbox"))
        self.horizontalLayout.addWidget(self.glbox)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.lay_right = QtGui.QVBoxLayout()
        self.lay_right.setObjectName(_fromUtf8("lay_right"))
        self.lbl_pos = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pos.sizePolicy().hasHeightForWidth())
        self.lbl_pos.setSizePolicy(sizePolicy)
        self.lbl_pos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pos.setObjectName(_fromUtf8("lbl_pos"))
        self.lay_right.addWidget(self.lbl_pos)
        self.lay_pos = QtGui.QHBoxLayout()
        self.lay_pos.setObjectName(_fromUtf8("lay_pos"))
        self.ln_pos = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_pos.sizePolicy().hasHeightForWidth())
        self.ln_pos.setSizePolicy(sizePolicy)
        self.ln_pos.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ln_pos.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_pos.setObjectName(_fromUtf8("ln_pos"))
        self.lay_pos.addWidget(self.ln_pos)
        self.btn_setpos = QtGui.QPushButton(self.centralwidget)
        self.btn_setpos.setObjectName(_fromUtf8("btn_setpos"))
        self.lay_pos.addWidget(self.btn_setpos)
        self.lay_right.addLayout(self.lay_pos)
        self.lbl_rot = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_rot.sizePolicy().hasHeightForWidth())
        self.lbl_rot.setSizePolicy(sizePolicy)
        self.lbl_rot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_rot.setObjectName(_fromUtf8("lbl_rot"))
        self.lay_right.addWidget(self.lbl_rot)
        self.lay_rot = QtGui.QHBoxLayout()
        self.lay_rot.setObjectName(_fromUtf8("lay_rot"))
        self.ln_rot = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_rot.sizePolicy().hasHeightForWidth())
        self.ln_rot.setSizePolicy(sizePolicy)
        self.ln_rot.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ln_rot.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_rot.setObjectName(_fromUtf8("ln_rot"))
        self.lay_rot.addWidget(self.ln_rot)
        self.btn_setrot = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_setrot.sizePolicy().hasHeightForWidth())
        self.btn_setrot.setSizePolicy(sizePolicy)
        self.btn_setrot.setObjectName(_fromUtf8("btn_setrot"))
        self.lay_rot.addWidget(self.btn_setrot)
        self.lay_right.addLayout(self.lay_rot)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.lay_right.addWidget(self.line_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.lay_right.addItem(spacerItem)
        self.lay_okc = QtGui.QHBoxLayout()
        self.lay_okc.setObjectName(_fromUtf8("lay_okc"))
        self.btn_okc = QtGui.QDialogButtonBox(self.centralwidget)
        self.btn_okc.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_okc.sizePolicy().hasHeightForWidth())
        self.btn_okc.setSizePolicy(sizePolicy)
        self.btn_okc.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.btn_okc.setObjectName(_fromUtf8("btn_okc"))
        self.lay_okc.addWidget(self.btn_okc, QtCore.Qt.AlignRight)
        self.lay_right.addLayout(self.lay_okc)
        self.horizontalLayout.addLayout(self.lay_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 34))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuShow = QtGui.QMenu(self.menuView)
        self.menuShow.setObjectName(_fromUtf8("menuShow"))
        self.menuVisual_Style = QtGui.QMenu(self.menuView)
        self.menuVisual_Style.setObjectName(_fromUtf8("menuVisual_Style"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuComponents = QtGui.QMenu(self.menubar)
        self.menuComponents.setGeometry(QtCore.QRect(666, 177, 192, 134))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuComponents.sizePolicy().hasHeightForWidth())
        self.menuComponents.setSizePolicy(sizePolicy)
        self.menuComponents.setMinimumSize(QtCore.QSize(150, 0))
        self.menuComponents.setObjectName(_fromUtf8("menuComponents"))
        self.menuAdd = QtGui.QMenu(self.menuComponents)
        self.menuAdd.setGeometry(QtCore.QRect(853, 180, 208, 134))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuAdd.sizePolicy().hasHeightForWidth())
        self.menuAdd.setSizePolicy(sizePolicy)
        self.menuAdd.setMinimumSize(QtCore.QSize(0, 0))
        self.menuAdd.setObjectName(_fromUtf8("menuAdd"))
        self.menuModify = QtGui.QMenu(self.menubar)
        self.menuModify.setObjectName(_fromUtf8("menuModify"))
        self.menuMa_terials = QtGui.QMenu(self.menubar)
        self.menuMa_terials.setObjectName(_fromUtf8("menuMa_terials"))
        MainWindow.setMenuBar(self.menubar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionPoints = QtGui.QAction(MainWindow)
        self.actionPoints.setObjectName(_fromUtf8("actionPoints"))
        self.actionFaces = QtGui.QAction(MainWindow)
        self.actionFaces.setObjectName(_fromUtf8("actionFaces"))
        self.actionLeft = QtGui.QAction(MainWindow)
        self.actionLeft.setObjectName(_fromUtf8("actionLeft"))
        self.actionRight = QtGui.QAction(MainWindow)
        self.actionRight.setObjectName(_fromUtf8("actionRight"))
        self.actionTop = QtGui.QAction(MainWindow)
        self.actionTop.setObjectName(_fromUtf8("actionTop"))
        self.actionBack = QtGui.QAction(MainWindow)
        self.actionBack.setObjectName(_fromUtf8("actionBack"))
        self.actionSolid = QtGui.QAction(MainWindow)
        self.actionSolid.setObjectName(_fromUtf8("actionSolid"))
        self.actionWireframe = QtGui.QAction(MainWindow)
        self.actionWireframe.setObjectName(_fromUtf8("actionWireframe"))
        self.actionLighting = QtGui.QAction(MainWindow)
        self.actionLighting.setCheckable(True)
        self.actionLighting.setObjectName(_fromUtf8("actionLighting"))
        self.actionActive_Armor = QtGui.QAction(MainWindow)
        self.actionActive_Armor.setObjectName(_fromUtf8("actionActive_Armor"))
        self.actionArrays = QtGui.QAction(MainWindow)
        self.actionArrays.setObjectName(_fromUtf8("actionArrays"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionDynamic_Armor = QtGui.QAction(MainWindow)
        self.actionDynamic_Armor.setObjectName(_fromUtf8("actionDynamic_Armor"))
        self.action_Constrain = QtGui.QAction(MainWindow)
        self.action_Constrain.setObjectName(_fromUtf8("action_Constrain"))
        self.actionManage = QtGui.QAction(MainWindow)
        self.actionManage.setObjectName(_fromUtf8("actionManage"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionClose_2 = QtGui.QAction(MainWindow)
        self.actionClose_2.setObjectName(_fromUtf8("actionClose_2"))
        self.actionEdit = QtGui.QAction(MainWindow)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionAdd_custom = QtGui.QAction(MainWindow)
        self.actionAdd_custom.setObjectName(_fromUtf8("actionAdd_custom"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionClose_2)
        self.menuShow.addAction(self.actionPoints)
        self.menuShow.addAction(self.actionFaces)
        self.menuShow.addAction(self.actionLeft)
        self.menuShow.addAction(self.actionRight)
        self.menuShow.addAction(self.actionTop)
        self.menuShow.addAction(self.actionBack)
        self.menuVisual_Style.addAction(self.actionSolid)
        self.menuVisual_Style.addAction(self.actionWireframe)
        self.menuView.addAction(self.menuShow.menuAction())
        self.menuView.addAction(self.menuVisual_Style.menuAction())
        self.menuView.addAction(self.actionLighting)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAdd.addAction(self.actionActive_Armor)
        self.menuAdd.addAction(self.actionDynamic_Armor)
        self.menuComponents.addAction(self.menuAdd.menuAction())
        self.menuComponents.addAction(self.actionDelete)
        self.menuModify.addAction(self.actionEdit)
        self.menuModify.addAction(self.action_Constrain)
        self.menuModify.addAction(self.actionArrays)
        self.menuMa_terials.addAction(self.actionManage)
        self.menuMa_terials.addAction(self.actionAdd_custom)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComponents.menuAction())
        self.menubar.addAction(self.menuModify.menuAction())
        self.menubar.addAction(self.menuMa_terials.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Constructor", None))
        self.lbl_pos.setText(_translate("MainWindow", "Component position (X,Y,Z)", None))
        self.ln_pos.setText(_translate("MainWindow", "0,0,0", None))
        self.btn_setpos.setText(_translate("MainWindow", "Set position", None))
        self.lbl_rot.setText(_translate("MainWindow", "Component Rotation angles ", None))
        self.ln_rot.setText(_translate("MainWindow", "0,0,0", None))
        self.btn_setrot.setText(_translate("MainWindow", "Set rotation", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuView.setTitle(_translate("MainWindow", "&View", None))
        self.menuShow.setTitle(_translate("MainWindow", "Views", None))
        self.menuVisual_Style.setTitle(_translate("MainWindow", "Visual Style", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Ab&out", None))
        self.menuComponents.setTitle(_translate("MainWindow", "&Components", None))
        self.menuAdd.setTitle(_translate("MainWindow", "&Add", None))
        self.menuModify.setTitle(_translate("MainWindow", "&Modify", None))
        self.menuMa_terials.setTitle(_translate("MainWindow", "Ma&terials", None))
        self.actionImport.setText(_translate("MainWindow", "Save as...", None))
        self.actionClose.setText(_translate("MainWindow", "Export...", None))
        self.actionPoints.setText(_translate("MainWindow", "Front", None))
        self.actionFaces.setText(_translate("MainWindow", "Back", None))
        self.actionLeft.setText(_translate("MainWindow", "Left", None))
        self.actionRight.setText(_translate("MainWindow", "Right", None))
        self.actionTop.setText(_translate("MainWindow", "Top", None))
        self.actionBack.setText(_translate("MainWindow", "Back", None))
        self.actionSolid.setText(_translate("MainWindow", "Solid", None))
        self.actionWireframe.setText(_translate("MainWindow", "Wireframe", None))
        self.actionLighting.setText(_translate("MainWindow", "Lighting", None))
        self.actionActive_Armor.setText(_translate("MainWindow", "&Base component", None))
        self.actionArrays.setText(_translate("MainWindow", "Arrays...", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionDynamic_Armor.setText(_translate("MainWindow", "&Dynamic Armor", None))
        self.action_Constrain.setText(_translate("MainWindow", "Co&nstrain...", None))
        self.actionManage.setText(_translate("MainWindow", "Manage...", None))
        self.actionLoad.setText(_translate("MainWindow", "Open...", None))
        self.actionClose_2.setText(_translate("MainWindow", "Close", None))
        self.actionEdit.setText(_translate("MainWindow", "Edit...", None))
        self.actionAdd_custom.setText(_translate("MainWindow", "Add custom...", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete...", None))

